export default[
    {
      key:'1',
      title:"首页",
      path:'/admin/home'
    },
    {
     key:'2',
     title:'用户管理',
     path:'/admin/user',
     children:[
       {
         key:'2-1',
         title:"用户添加",
         path:'/admin/useradd'
        },
       {
        key:'2-2',
        title:"用户列表",
        path:'/admin/userlist'
      }
     ]
    },
    {
      key:'3',
      title:"商品管理",
      path:'/admin/goods',
      children:[
        {
          key:'3-1',
          title:'商品信息',
          path:'/admin/goodsInfo'
        },
        {
          key:'3-2',
          title:'商品类别',
          path:'/admin/goodsKind'
        }
      ]
    },
    {
      key:'8',
      title:"管理员",
      path:'/admin/administrator'
    },
    {
      key:'9',
      title:"设置",
      path:'/admin/set'
    },
  ]